# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javadoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew javadoc
    - name: GitHub Pages Javadoc
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: build/docs/javadoc
        target_branch: gh-pages
        keep_history: false
      env:
        GITHUB_PAT: ${{ secrets.pat }}
